# Generated by Django 3.2.18 on 2023-06-15 02:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sertif', '0004_uploadedfile_slug'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UploadedFile',
        ),
    ]
