# Generated by Django 3.2.18 on 2023-06-15 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sertif', '0008_auto_20230615_1731'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certification',
            name='batch',
        ),
        migrations.RemoveField(
            model_name='certification',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='certification',
            name='no_participant',
        ),
        migrations.RemoveField(
            model_name='certification',
            name='status',
        ),
        migrations.RemoveField(
            model_name='certification',
            name='type_certification',
        ),
        migrations.AddField(
            model_name='certification',
            name='idd',
            field=models.CharField(default=0, max_length=2),
            preserve_default=False,
        ),
    ]
