# Generated by Django 3.2.18 on 2023-06-15 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sertif', '0009_auto_20230615_1735'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certification',
            name='idd',
        ),
        migrations.AddField(
            model_name='certification',
            name='batch',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='certification',
            name='full_name',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='certification',
            name='no_participant',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='certification',
            name='status',
            field=models.CharField(default=90, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='certification',
            name='type_certification',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
    ]
