# Generated by Django 3.2.18 on 2023-06-24 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sertif', '0011_mikrotikcertification'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MikroTikCertification',
            new_name='LecturerCertification',
        ),
    ]
